// Generated by gencpp from file interact_msg_srv/PointCloud.msg
// DO NOT EDIT!


#ifndef INTERACT_MSG_SRV_MESSAGE_POINTCLOUD_H
#define INTERACT_MSG_SRV_MESSAGE_POINTCLOUD_H

#include <ros/service_traits.h>


#include <interact_msg_srv/PointCloudRequest.h>
#include <interact_msg_srv/PointCloudResponse.h>


namespace interact_msg_srv
{

struct PointCloud
{

typedef PointCloudRequest Request;
typedef PointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PointCloud
} // namespace interact_msg_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interact_msg_srv::PointCloud > {
  static const char* value()
  {
    return "2a538a6bfd3558365d95b62ad54c313a";
  }

  static const char* value(const ::interact_msg_srv::PointCloud&) { return value(); }
};

template<>
struct DataType< ::interact_msg_srv::PointCloud > {
  static const char* value()
  {
    return "interact_msg_srv/PointCloud";
  }

  static const char* value(const ::interact_msg_srv::PointCloud&) { return value(); }
};


// service_traits::MD5Sum< ::interact_msg_srv::PointCloudRequest> should match 
// service_traits::MD5Sum< ::interact_msg_srv::PointCloud > 
template<>
struct MD5Sum< ::interact_msg_srv::PointCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interact_msg_srv::PointCloud >::value();
  }
  static const char* value(const ::interact_msg_srv::PointCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interact_msg_srv::PointCloudRequest> should match 
// service_traits::DataType< ::interact_msg_srv::PointCloud > 
template<>
struct DataType< ::interact_msg_srv::PointCloudRequest>
{
  static const char* value()
  {
    return DataType< ::interact_msg_srv::PointCloud >::value();
  }
  static const char* value(const ::interact_msg_srv::PointCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interact_msg_srv::PointCloudResponse> should match 
// service_traits::MD5Sum< ::interact_msg_srv::PointCloud > 
template<>
struct MD5Sum< ::interact_msg_srv::PointCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interact_msg_srv::PointCloud >::value();
  }
  static const char* value(const ::interact_msg_srv::PointCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interact_msg_srv::PointCloudResponse> should match 
// service_traits::DataType< ::interact_msg_srv::PointCloud > 
template<>
struct DataType< ::interact_msg_srv::PointCloudResponse>
{
  static const char* value()
  {
    return DataType< ::interact_msg_srv::PointCloud >::value();
  }
  static const char* value(const ::interact_msg_srv::PointCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERACT_MSG_SRV_MESSAGE_POINTCLOUD_H
