set(_CATKIN_CURRENT_PACKAGE "gesture_recog")
set(gesture_recog_VERSION "1.0.0")
set(gesture_recog_MAINTAINER "Hujun <hujun1413@foxmail.com>")
set(gesture_recog_PACKAGE_FORMAT "2")
set(gesture_recog_BUILD_DEPENDS "roscpp" "rosconsole" "std_srvs" "message_generation" "interact_msg_srv")
set(gesture_recog_BUILD_EXPORT_DEPENDS )
set(gesture_recog_BUILDTOOL_DEPENDS "catkin")
set(gesture_recog_BUILDTOOL_EXPORT_DEPENDS )
set(gesture_recog_EXEC_DEPENDS "interact_msg_srv" "message_runtime" "roscpp" "rosconsole" "std_srvs")
set(gesture_recog_RUN_DEPENDS "interact_msg_srv" "message_runtime" "roscpp" "rosconsole" "std_srvs")
set(gesture_recog_TEST_DEPENDS )
set(gesture_recog_DOC_DEPENDS )
set(gesture_recog_DEPRECATED "")