// Generated by gencpp from file tzc_transport/findHandleResponse.msg
// DO NOT EDIT!


#ifndef TZC_TRANSPORT_MESSAGE_FINDHANDLERESPONSE_H
#define TZC_TRANSPORT_MESSAGE_FINDHANDLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tzc_transport
{
template <class ContainerAllocator>
struct findHandleResponse_
{
  typedef findHandleResponse_<ContainerAllocator> Type;

  findHandleResponse_()
    : data_handle(0)  {
    }
  findHandleResponse_(const ContainerAllocator& _alloc)
    : data_handle(0)  {
  (void)_alloc;
    }



   typedef int64_t _data_handle_type;
  _data_handle_type data_handle;




  typedef boost::shared_ptr< ::tzc_transport::findHandleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tzc_transport::findHandleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct findHandleResponse_

typedef ::tzc_transport::findHandleResponse_<std::allocator<void> > findHandleResponse;

typedef boost::shared_ptr< ::tzc_transport::findHandleResponse > findHandleResponsePtr;
typedef boost::shared_ptr< ::tzc_transport::findHandleResponse const> findHandleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tzc_transport::findHandleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tzc_transport::findHandleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tzc_transport

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tzc_transport::findHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tzc_transport::findHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tzc_transport::findHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tzc_transport::findHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tzc_transport::findHandleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tzc_transport::findHandleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tzc_transport::findHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e3eb42f6b126ec607f609ce8ba4689f";
  }

  static const char* value(const ::tzc_transport::findHandleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e3eb42f6b126ec6ULL;
  static const uint64_t static_value2 = 0x07f609ce8ba4689fULL;
};

template<class ContainerAllocator>
struct DataType< ::tzc_transport::findHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tzc_transport/findHandleResponse";
  }

  static const char* value(const ::tzc_transport::findHandleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tzc_transport::findHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 data_handle\n\
\n\
";
  }

  static const char* value(const ::tzc_transport::findHandleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tzc_transport::findHandleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_handle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct findHandleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tzc_transport::findHandleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tzc_transport::findHandleResponse_<ContainerAllocator>& v)
  {
    s << indent << "data_handle: ";
    Printer<int64_t>::stream(s, indent + "  ", v.data_handle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TZC_TRANSPORT_MESSAGE_FINDHANDLERESPONSE_H
