// Generated by gencpp from file tzc_transport/findHandle.msg
// DO NOT EDIT!


#ifndef TZC_TRANSPORT_MESSAGE_FINDHANDLE_H
#define TZC_TRANSPORT_MESSAGE_FINDHANDLE_H

#include <ros/service_traits.h>


#include <tzc_transport/findHandleRequest.h>
#include <tzc_transport/findHandleResponse.h>


namespace tzc_transport
{

struct findHandle
{

typedef findHandleRequest Request;
typedef findHandleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct findHandle
} // namespace tzc_transport


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tzc_transport::findHandle > {
  static const char* value()
  {
    return "72658d7436d535dac18c2c6563a14a73";
  }

  static const char* value(const ::tzc_transport::findHandle&) { return value(); }
};

template<>
struct DataType< ::tzc_transport::findHandle > {
  static const char* value()
  {
    return "tzc_transport/findHandle";
  }

  static const char* value(const ::tzc_transport::findHandle&) { return value(); }
};


// service_traits::MD5Sum< ::tzc_transport::findHandleRequest> should match 
// service_traits::MD5Sum< ::tzc_transport::findHandle > 
template<>
struct MD5Sum< ::tzc_transport::findHandleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tzc_transport::findHandle >::value();
  }
  static const char* value(const ::tzc_transport::findHandleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tzc_transport::findHandleRequest> should match 
// service_traits::DataType< ::tzc_transport::findHandle > 
template<>
struct DataType< ::tzc_transport::findHandleRequest>
{
  static const char* value()
  {
    return DataType< ::tzc_transport::findHandle >::value();
  }
  static const char* value(const ::tzc_transport::findHandleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tzc_transport::findHandleResponse> should match 
// service_traits::MD5Sum< ::tzc_transport::findHandle > 
template<>
struct MD5Sum< ::tzc_transport::findHandleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tzc_transport::findHandle >::value();
  }
  static const char* value(const ::tzc_transport::findHandleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tzc_transport::findHandleResponse> should match 
// service_traits::DataType< ::tzc_transport::findHandle > 
template<>
struct DataType< ::tzc_transport::findHandleResponse>
{
  static const char* value()
  {
    return DataType< ::tzc_transport::findHandle >::value();
  }
  static const char* value(const ::tzc_transport::findHandleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TZC_TRANSPORT_MESSAGE_FINDHANDLE_H
