// Generated by gencpp from file tzc_transport/findHandleRequest.msg
// DO NOT EDIT!


#ifndef TZC_TRANSPORT_MESSAGE_FINDHANDLEREQUEST_H
#define TZC_TRANSPORT_MESSAGE_FINDHANDLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tzc_transport
{
template <class ContainerAllocator>
struct findHandleRequest_
{
  typedef findHandleRequest_<ContainerAllocator> Type;

  findHandleRequest_()
    : timeStamp()  {
    }
  findHandleRequest_(const ContainerAllocator& _alloc)
    : timeStamp()  {
  (void)_alloc;
    }



   typedef ros::Time _timeStamp_type;
  _timeStamp_type timeStamp;




  typedef boost::shared_ptr< ::tzc_transport::findHandleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tzc_transport::findHandleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct findHandleRequest_

typedef ::tzc_transport::findHandleRequest_<std::allocator<void> > findHandleRequest;

typedef boost::shared_ptr< ::tzc_transport::findHandleRequest > findHandleRequestPtr;
typedef boost::shared_ptr< ::tzc_transport::findHandleRequest const> findHandleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tzc_transport::findHandleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tzc_transport::findHandleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tzc_transport

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tzc_transport::findHandleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tzc_transport::findHandleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tzc_transport::findHandleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tzc_transport::findHandleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tzc_transport::findHandleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tzc_transport::findHandleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tzc_transport::findHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ce054600bab7f9c058d36926a925c54";
  }

  static const char* value(const ::tzc_transport::findHandleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ce054600bab7f9cULL;
  static const uint64_t static_value2 = 0x058d36926a925c54ULL;
};

template<class ContainerAllocator>
struct DataType< ::tzc_transport::findHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tzc_transport/findHandleRequest";
  }

  static const char* value(const ::tzc_transport::findHandleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tzc_transport::findHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timeStamp\n\
";
  }

  static const char* value(const ::tzc_transport::findHandleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tzc_transport::findHandleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeStamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct findHandleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tzc_transport::findHandleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tzc_transport::findHandleRequest_<ContainerAllocator>& v)
  {
    s << indent << "timeStamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timeStamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TZC_TRANSPORT_MESSAGE_FINDHANDLEREQUEST_H
