// Generated by gencpp from file kinect2_viewer/PointCloud.msg
// DO NOT EDIT!


#ifndef KINECT2_VIEWER_MESSAGE_POINTCLOUD_H
#define KINECT2_VIEWER_MESSAGE_POINTCLOUD_H

#include <ros/service_traits.h>


#include <kinect2_viewer/PointCloudRequest.h>
#include <kinect2_viewer/PointCloudResponse.h>


namespace kinect2_viewer
{

struct PointCloud
{

typedef PointCloudRequest Request;
typedef PointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PointCloud
} // namespace kinect2_viewer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinect2_viewer::PointCloud > {
  static const char* value()
  {
    return "2a538a6bfd3558365d95b62ad54c313a";
  }

  static const char* value(const ::kinect2_viewer::PointCloud&) { return value(); }
};

template<>
struct DataType< ::kinect2_viewer::PointCloud > {
  static const char* value()
  {
    return "kinect2_viewer/PointCloud";
  }

  static const char* value(const ::kinect2_viewer::PointCloud&) { return value(); }
};


// service_traits::MD5Sum< ::kinect2_viewer::PointCloudRequest> should match 
// service_traits::MD5Sum< ::kinect2_viewer::PointCloud > 
template<>
struct MD5Sum< ::kinect2_viewer::PointCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinect2_viewer::PointCloud >::value();
  }
  static const char* value(const ::kinect2_viewer::PointCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinect2_viewer::PointCloudRequest> should match 
// service_traits::DataType< ::kinect2_viewer::PointCloud > 
template<>
struct DataType< ::kinect2_viewer::PointCloudRequest>
{
  static const char* value()
  {
    return DataType< ::kinect2_viewer::PointCloud >::value();
  }
  static const char* value(const ::kinect2_viewer::PointCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinect2_viewer::PointCloudResponse> should match 
// service_traits::MD5Sum< ::kinect2_viewer::PointCloud > 
template<>
struct MD5Sum< ::kinect2_viewer::PointCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinect2_viewer::PointCloud >::value();
  }
  static const char* value(const ::kinect2_viewer::PointCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinect2_viewer::PointCloudResponse> should match 
// service_traits::DataType< ::kinect2_viewer::PointCloud > 
template<>
struct DataType< ::kinect2_viewer::PointCloudResponse>
{
  static const char* value()
  {
    return DataType< ::kinect2_viewer::PointCloud >::value();
  }
  static const char* value(const ::kinect2_viewer::PointCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINECT2_VIEWER_MESSAGE_POINTCLOUD_H
