// Generated by gencpp from file kinect2_viewer/PointCloudRequest.msg
// DO NOT EDIT!


#ifndef KINECT2_VIEWER_MESSAGE_POINTCLOUDREQUEST_H
#define KINECT2_VIEWER_MESSAGE_POINTCLOUDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinect2_viewer
{
template <class ContainerAllocator>
struct PointCloudRequest_
{
  typedef PointCloudRequest_<ContainerAllocator> Type;

  PointCloudRequest_()
    : a()  {
    }
  PointCloudRequest_(const ContainerAllocator& _alloc)
    : a()  {
  (void)_alloc;
    }



   typedef ros::Time _a_type;
  _a_type a;




  typedef boost::shared_ptr< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloudRequest_

typedef ::kinect2_viewer::PointCloudRequest_<std::allocator<void> > PointCloudRequest;

typedef boost::shared_ptr< ::kinect2_viewer::PointCloudRequest > PointCloudRequestPtr;
typedef boost::shared_ptr< ::kinect2_viewer::PointCloudRequest const> PointCloudRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinect2_viewer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5d6340060c5ab7a6af94375fd3a7d11";
  }

  static const char* value(const ::kinect2_viewer::PointCloudRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5d6340060c5ab7aULL;
  static const uint64_t static_value2 = 0x6af94375fd3a7d11ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect2_viewer/PointCloudRequest";
  }

  static const char* value(const ::kinect2_viewer::PointCloudRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time a\n\
";
  }

  static const char* value(const ::kinect2_viewer::PointCloudRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloudRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect2_viewer::PointCloudRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinect2_viewer::PointCloudRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINECT2_VIEWER_MESSAGE_POINTCLOUDREQUEST_H
